defaults:
  logdir: runs/wm_dreamerv3
  seed: 0
  task: carla_navigation
  num_envs: 1
  device: cuda
  precision: 16-mixed
  gradient_checkpointing: True

  dynamics_type: "rssm"
  policy_type: "default_policy"
  actor_model_type: "default_actor"
  num_actions: 28
  diffusion_steps: 10
  stoch_size: 32
  discrete: 32
  hidden_size: 768
  num_blocks_trans: 3
  att_context_left: 24

  # Neural Network Capacity
  dim_cnn: 32
  encoder_dim_layers: [32, 64, 128, 256]
  decoder_dim_layers: [256, 128, 64, 32, 3]

  contrastive_steps: 1
  contrastive_offsets: [15]
  uniform_mix: 0.01

  # Replay Buffer
  replay_size: 100000

  # Run Control
  steps: 200000
  eval_every: 200
  eval_episodes: 1
  log_every: 10
  save_every: 400
  train_ratio: 512
  train_fill: 500
  replay_min: 500
  tensorboard: False
  wandb: True
  wandb_project: "carTwister-dreamerv3"

  run:
    script: train
    expl_until: 5000
    eval_initial: True
    eval_samples: 1
    eval_fill: 0
    actor_dist_disc: onehot
    actor_entropy: 0.003
    actor_dist_cont: normal
    actor_grad_disc: reinforce
    actor_grad_cont: backprop
    critic_type: vfunction
    imag_horizon: 15
    imag_unroll: False
    entropy: 0.01
    discount_lambda: 0.95
    critic_slowreg: logprob
    slow_critic_update: 1
    slow_critic_fraction: 0.02
    retnorm: { impl: perc_ema, decay: 0.99, max: 1.0, perclo: 5.0, perchi: 95.0 }
    actent: 0.0003
    imag_smoothness_scale: 0.0001
    sync_every: 10
    log_zeros: False
    log_keys_video: ["camera"]
    log_keys_sum: "^$"
    log_keys_mean: "(log_entropy)"
    log_keys_max: "^$"
    from_checkpoint: ""

  # Optimization (DreamerV3 style)
  model_opt:
    {
      opt: adam,
      lr: 0.0001,
      eps: 0.00000001,
      clip: 1000.0,
      wd: 0.0,
      warmup: 0,
      decay_steps: 50000000,
      min_lr: 0.00004,
      lateclip: 0.0,
    }
  actor_opt:
    {
      opt: adam,
      lr: 0.00003,
      eps: 0.00001,
      clip: 100.0,
      wd: 0.0,
      warmup: 0,
      decay_steps: 50000000,
      min_lr: 0.00001,
      lateclip: 0.0,
    }
  critic_opt:
    {
      opt: adam,
      lr: 0.00003,
      eps: 0.00001,
      clip: 100.0,
      wd: 0.0,
      warmup: 0,
      decay_steps: 50000000,
      min_lr: 0.00001,
      lateclip: 0.0,
    }

  # Agent Architecture Details
  reward_head:
    {
      layers: 3,
      units: 512,
      act: silu,
      norm: layer,
      dist: symlog_disc,
      outscale: 0.0,
      outnorm: False,
      inputs: [deter, stoch],
      winit: normal,
      fan: avg,
      bins: 255,
    }
  cont_head:
    {
      layers: 3,
      units: 512,
      act: silu,
      norm: layer,
      dist: binary,
      outscale: 1.0,
      outnorm: False,
      inputs: [deter, stoch],
      winit: normal,
      fan: avg,
    }

  actor:
    {
      layers: 3,
      units: 512,
      act: silu,
      norm: layer,
      minstd: 0.1,
      maxstd: 1.0,
      outscale: 1.0,
      outnorm: False,
      unimix: 0.01,
      inputs: [deter, stoch],
      entropy: 0.3,
      winit: normal,
      fan: avg,
      symlog_inputs: False,
    }
  critic:
    {
      layers: 3,
      units: 512,
      act: silu,
      norm: layer,
      dist: symlog_disc,
      outscale: 0.0,
      outnorm: False,
      inputs: [deter, stoch],
      winit: normal,
      fan: avg,
      bins: 255,
      symlog_inputs: False,
    }

  # Loss Scales
  loss_scales:
    {
      image: 1.5,
      vector: 1.0,
      reward: 1.0,
      cont: 1.0,
      dyn: 0.5,
      rep: 0.1,
      actor: 1.0,
      critic: 1.0,
      slowreg: 1.0,
    }

  # Modules & Losses
  modules:
    losses:
      kl: { enabled: true, weight: 1.0, free_nats: 1.0, prior_scale: 0.5, post_scale: 0.1 }
      reconstruction: { enabled: true, weight: 1.0 }
      joint_embedding: { enabled: false, weight: 0.2 }
      reward: { enabled: true, weight: 1.0 }
      discount: { enabled: true, weight: 1.0 }
      sigreg: { enabled: false, weight: 0.1 }
      cpc: { enabled: true, weight: 1.0 }

  # Agent Params
  task_behavior: Greedy
  expl_behavior: None
  batch_size: 20
  batch_length: 64
  data_loaders: 20
  H: 15
  gamma: 0.997
  lambda_td: 0.95
  actent: 0.0003
  target_value_reg: True

  # Wrapper Config
  wrapper:
    repeat: 4
    discretize: 0
    length: 1500
    reset: True
    checks: False

  # CARLA Env Params
  env_params:
    action:
      discrete_acc: [-2.0, 0.0, 1.0, 2.0]
      discrete_steer: [-0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6]
    reward:
      desired_speed: 4.0
    observation:
      camera:
        shape: [64, 64, 3]
        decode: True
        tssm: True
        pretrained: { enabled: false }
        cnn_blocks: 1
        encoder_dim_layers: [32, 64, 128, 256]
        decoder_dim_layers: [256, 128, 64, 32, 3]
        attributes: { image_size: 64, image_size_x: 64, image_size_y: 64 }
      birdeye_wpt:
        shape: [64, 64, 3]
        tssm: true
        decode: true
        pretrained: { enabled: false }
        cnn_blocks: 1
        encoder_dim_layers: [32, 64, 128, 256]
        decoder_dim_layers: [256, 128, 64, 32, 3]
        attributes: { image_size: 64, image_size_x: 64, image_size_y: 64 }

    dynamics_model:
      hidden_size: 512
      num_blocks: 2

    reward_model:
      layers: 3
      units: 512
      lidar: { tssm: false, decode: false }
    world:
      carla_port: 2000
      town: Town01
      fixed_delta_seconds: 0.05
